# Generated by Django 5.2.16 on 2026-07-13 09:29

import tuckit.core.models.accounts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_workspace_onboarding_dismissed'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', tuckit.core.models.accounts.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
