# Generated by Django 5.2.16 on 2026-07-16 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_workspace_onboarding_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='')),
                ('constraints', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('human', 'Human'), ('agent', 'Agent')], default='human', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='core.slice')),
            ],
        ),
    ]
