# Generated by Django 5.2.16 on 2026-07-17 10:53

from django.db import migrations, models


def copy_from_first_workspace(apps, schema_editor):
    """Each org's settings come from its oldest workspace. In practice every org has
    exactly one (create_org made it), but take the oldest deterministically rather
    than assume."""
    Org = apps.get_model("core", "Org")
    Workspace = apps.get_model("core", "Workspace")
    for org in Org.objects.all().iterator():
        ws = Workspace.objects.filter(org=org).order_by("id").first()
        if ws is None:
            continue
        org.description = ws.description
        org.onboarding_dismissed = ws.onboarding_dismissed
        org.onboarding_completed = ws.onboarding_completed
        org.shipped_board_mode = ws.shipped_board_mode
        org.shipped_board_limit = ws.shipped_board_limit
        org.save(update_fields=[
            "description", "onboarding_dismissed", "onboarding_completed",
            "shipped_board_mode", "shipped_board_limit",
        ])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bite_plan_finalize'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='org',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='org',
            name='onboarding_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='org',
            name='shipped_board_limit',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='org',
            name='shipped_board_mode',
            field=models.CharField(choices=[('count', 'Count'), ('days', 'Days')], default='count', max_length=5),
        ),
        migrations.AddField(
            model_name='org',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(copy_from_first_workspace, noop),
    ]
