# Generated by Django 5.2.16 on 2026-07-20 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_socialaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='target_type',
            field=models.CharField(choices=[('slice', 'Slice'), ('bite', 'Bite'), ('area', 'Area'), ('ticket', 'Ticket')], max_length=10),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='verb',
            field=models.CharField(choices=[('created', 'created'), ('status_changed', 'status changed'), ('triaged', 'triaged'), ('moved', 'moved'), ('shipped', 'shipped'), ('dropped', 'dropped'), ('planned', 'planned'), ('noted', 'noted'), ('promoted', 'promoted'), ('closed', 'closed')], max_length=20),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('human', 'Human'), ('agent', 'Agent')], default='human', max_length=10)),
                ('external_key', models.CharField(blank=True, default='', max_length=200)),
                ('rank', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.area')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to='core.orgmember')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.org')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddField(
            model_name='slice',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slice', to='core.ticket'),
        ),
    ]
