# Generated by Django 5.2.16 on 2026-07-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_convert_idea_slices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='is_triage',
        ),
        migrations.AlterField(
            model_name='slice',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('building', 'Building'), ('shipped', 'Shipped'), ('dropped', 'Dropped')], default='planned', max_length=10),
        ),
    ]
