# Generated by Django 5.2.16 on 2026-07-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_orgmember_home_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='verb',
            field=models.CharField(choices=[('created', 'created'), ('status_changed', 'status changed'), ('moved', 'moved'), ('shipped', 'shipped'), ('dropped', 'dropped'), ('planned', 'planned'), ('noted', 'noted'), ('promoted', 'promoted'), ('dismissed', 'dismissed'), ('deleted', 'deleted'), ('triaged', 'triaged'), ('closed', 'closed')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['org', 'id'], name='core_activi_org_id_750a22_idx'),
        ),
    ]
